pipeline:
  frontend:
    image: node
    commands:
      - cd client
      - npm i
      - npm test

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test