pipeline:
  frontend:
    image: node
    commands:
      - npm i
      - npm test

  publish-api-docker:
    registry: docker.io
    image: plugins/docker
    repo: ihreskiv/squaregame
    tags: latest
    secrets: [dockerhub_username, dockerhub_password]
