pipeline:
  frontend:
    image: node
    commands:
      - npm i
      - npm test

  publish-api-docker:
    image: plugins/docker:1.12
    username: $$DOCKERHUB_USERNAME
    password: $$DOCKERHUB_PASSWORD
    email: $$DOCKERHUB_EMAIL
    repo: ihreskiv/squaregame
    tags: latest
